import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,Check} from '@phosphor-icons/react';
import {api,formatMoney,loadSession,type SessionUser} from './api';
import {Brand,navigate} from './App';
import {themeById} from './data';
import {loadDraft} from './storage';
import CustomerOtpAuth from './CustomerOtpAuth';
import './checkout-commerce.css';
import './checkout-otp.css';

async function loadRazorpay(){if(window.Razorpay)return true;return new Promise<boolean>(resolve=>{const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.async=true;script.onload=()=>resolve(true);script.onerror=()=>resolve(false);document.head.appendChild(script)})}
const clean=(value:string)=>value.toLowerCase().replace(/[^a-z0-9-]/g,'').replace(/^-+|-+$/g,'').slice(0,40);

export default function Checkout(){
 const [draft]=useState(loadDraft);const theme=themeById(draft.theme);const [user,setUser]=useState<SessionUser|null>(null);const [code,setCode]=useState('');const [subdomain,setSubdomain]=useState(()=>clean(`${draft.name1}-${draft.name2}`));const [availability,setAvailability]=useState<'idle'|'checking'|'available'|'taken'>('idle');const [quote,setQuote]=useState<{subtotalCents:number;discountCents:number;taxCents:number;totalCents:number}|null>(null);const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{document.title='Checkout | Vowvel';loadSession().then(setUser).catch(()=>undefined)},[]);
 useEffect(()=>{if(subdomain.length<3){setAvailability('idle');return}setAvailability('checking');const timer=setTimeout(()=>api<{available:boolean}>(`/api/subdomains/${encodeURIComponent(subdomain)}`).then(result=>setAvailability(result.available?'available':'taken')).catch(()=>setAvailability('idle')),350);return()=>clearTimeout(timer)},[subdomain]);
 async function applyCoupon(){setBusy(true);setError('');try{const result=await api<{quote:typeof quote;coupon:{code:string}|null}>('/api/coupons/quote',{method:'POST',body:JSON.stringify({code})});setQuote(result.quote);setMessage(result.coupon?`${result.coupon.code} applied.`:'Price refreshed.')}catch(reason){setError(reason instanceof Error?reason.message:'Coupon could not be applied')}finally{setBusy(false)}}
 async function placeOrder(){if(!user||availability!=='available'){setError('Sign in and choose an available invitation address.');return}setBusy(true);setError('');setMessage('');try{const result=await api<{order:{id:string;totalCents:number;currency:string;providerOrderId:string|null;checkoutKey:string|null;invitationUrl:string};paymentConfigured:boolean;complimentary:boolean}>('/api/orders',{method:'POST',body:JSON.stringify({code,subdomain,invitation:{version:1,data:draft}})});if(result.complimentary){setMessage(`Your complimentary invitation is live at ${result.order.invitationUrl}.`);return}if(!result.paymentConfigured||!result.order.providerOrderId||!result.order.checkoutKey){setMessage(`Order ${result.order.id} is ready at ${result.order.invitationUrl}. Add Razorpay secrets to enable payment.`);return}if(!await loadRazorpay())throw new Error('Payment window could not be loaded');await new Promise<void>(resolve=>{let completed=false;const checkout=new window.Razorpay!({key:result.order.checkoutKey!,amount:result.order.totalCents,currency:result.order.currency,name:'Vowvel',description:`${theme.name} invitation`,order_id:result.order.providerOrderId!,handler:async response=>{completed=true;try{await api('/api/verify-payment',{method:'POST',body:JSON.stringify({orderId:result.order.id,...response})});setMessage(`Payment verified. Your invitation will be available at ${result.order.invitationUrl} once Razorpay confirms capture.`)}catch(reason){setError(reason instanceof Error?reason.message:'Payment could not be verified')}finally{resolve()}},prefill:{name:user.name,email:user.email},theme:{color:'#43523c'},modal:{ondismiss:()=>{if(!completed)setError('Payment was cancelled. You have not been charged.');resolve()}}});checkout.on('payment.failed',response=>setError(response.error?.description||response.error?.reason||'Payment failed. Please try again.'));checkout.open()})}catch(reason){setError(reason instanceof Error?reason.message:'Order could not be created')}finally{setBusy(false)}}
 const shown=quote||{subtotalCents:249900,discountCents:0,taxCents:0,totalCents:249900};
 return <div className="checkout-page"><header className="editor-header"><Brand/><button className="text-button" onClick={()=>navigate('/create/'+draft.theme)}><ArrowLeft/> Back to your invitation</button></header><main className="checkout-layout wrap"><div><span className="eyebrow">THE FINAL LITTLE STEP</span><h1>Ready for<br/><em>your people.</em></h1><p>Your invitation is saved on this device.<br/>Take one more look before the big hello.</p><div className={`checkout-preview ${draft.theme}`} style={{background:theme.paper,color:theme.color}}><img src={theme.art} alt="Your selected design" width="1086" height="1448"/><div><span>{draft.occasion.toUpperCase()}</span><h2>{draft.name1||'Your name'} <i>&</i><br/>{draft.name2||'Their name'}</h2><p>{theme.name}</p></div></div><button className="text-link" onClick={()=>navigate('/preview/draft')}>Preview the live design <ArrowUpRight size={18}/></button></div><section className="checkout-summary"><span className="eyebrow">SECURE CHECKOUT</span><h2>One lovely invitation.</h2>{!user?<CustomerOtpAuth compact onAuthenticated={setUser}/>:<p className="checkout-signed-in"><Check size={16}/> Signed in as {user.email}</p>}<label className="subdomain-field"><span>Your invitation address</span><div><input value={subdomain} onChange={event=>setSubdomain(clean(event.target.value))}/><strong>.vowvel.com</strong></div><small id="subdomain-status" className={availability}>{availability==='checking'?'Checking…':availability==='available'?'Available':availability==='taken'?'Already taken. Try another.':'Use 3–40 letters, numbers or hyphens.'}</small></label><div className="coupon-entry"><label>Coupon code<input value={code} onChange={event=>setCode(event.target.value.toUpperCase())}/></label><button onClick={()=>void applyCoupon()} disabled={busy||!code}>Apply</button></div><div className="order-line"><span>{theme.name}<small>{draft.occasion} invitation</small></span><strong>{formatMoney(shown.subtotalCents)}</strong></div><div className="price-breakdown">{shown.discountCents>0&&<span>Coupon discount <strong>-{formatMoney(shown.discountCents)}</strong></span>}{shown.taxCents>0&&<span>Tax <strong>{formatMoney(shown.taxCents)}</strong></span>}</div><div className="order-total"><span>Total</span><strong>{formatMoney(shown.totalCents)}</strong></div>{error&&<p className="notice checkout-error" role="alert">{error}</p>}{message&&<p className="notice">{message}</p>}<button className="button full" onClick={()=>void placeOrder()} disabled={busy||!user||availability!=='available'}>{busy?'Please wait':shown.totalCents===0?'Publish invitation':'Continue to payment'} <ArrowRight/></button></section></main></div>;
}
