import { useEffect, useRef, useState, type ChangeEvent } from 'react';
import { emptyCouple, type CoupleDetails, type CoupleProfile } from './data';
export default function CoupleEditor({ names, value, onChange }: { names: [string,string]; value?: CoupleDetails; onChange: (value: CoupleDetails) => void }) {
 const couple=value||emptyCouple();const [busy,setBusy]=useState<number|null>(null);const [error,setError]=useState('');const inputs=useRef<(HTMLInputElement|null)[]>([]);
 const mounted=useRef(true);const generation=useRef(0);const latest=useRef({couple,onChange});latest.current={couple,onChange};
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;generation.current++}},[]);
 useEffect(()=>{generation.current++},[value,names[0],names[1]]);
 const patch=(index:number,partial:Partial<CoupleProfile>)=>{const live=latest.current;live.onChange({...live.couple,profiles:live.couple.profiles.map((profile,i)=>i===index?{...profile,...partial}:profile) as CoupleDetails['profiles']})};
 async function upload(event:ChangeEvent<HTMLInputElement>,index:number){const file=event.target.files?.[0];event.target.value='';if(!file)return;const request=++generation.current;setBusy(index);setError('');try{if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Choose a JPG, PNG or WebP portrait.');if(file.size>12*1024*1024)throw Error('Choose a portrait smaller than 12 MB.');const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');const scale=Math.min(1,800/Math.max(image.width,image.height));canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const context=canvas.getContext('2d');if(!context)throw Error('Photo processing is unavailable.');context.drawImage(image,0,0,canvas.width,canvas.height);if(mounted.current&&request===generation.current)patch(index,{photo:canvas.toDataURL('image/jpeg',.78)});}finally{URL.revokeObjectURL(url)}}catch(e){if(mounted.current&&request===generation.current)setError(e instanceof Error?e.message:'Unable to load that portrait.')}finally{if(mounted.current)setBusy(null)}}
 return <div className="couple-editor"><h3 className="section-toggle-title">The people behind the promises.</h3><label className="toggle-row"><span>Introduce the couple</span><input type="checkbox" disabled={busy!==null} checked={couple.enabled} onChange={e=>onChange({...couple,enabled:e.target.checked})}/></label>{couple.enabled&&<><p className="field-note-text">A portrait, a few words, and the people who shaped you. Every detail is optional.</p><label className="toggle-row"><span>Include family details</span><input type="checkbox" disabled={busy!==null} checked={couple.showFamily} onChange={e=>onChange({...couple,showFamily:e.target.checked})}/></label>{error&&<p className="editor-error" role="alert">{error}</p>}{couple.profiles.map((profile,index)=><fieldset className="event-editor" key={index} disabled={busy!==null}><legend>{names[index]||`Person ${index+1}`}</legend><label className="field"><span>How you’d like to be introduced <small>(optional)</small></span><input value={profile.role} maxLength={45} placeholder="e.g. The bride, The groom, or leave blank" onChange={e=>patch(index,{role:e.target.value})}/></label><input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" ref={node=>{inputs.current[index]=node;}} aria-label={`Choose portrait of ${names[index]||`person ${index+1}`}`} onChange={e=>upload(e,index)}/>{profile.photo&&<img src={profile.photo} alt={`Portrait of ${names[index]||`person ${index+1}`}`} style={{width:110,height:140,objectFit:'cover',display:'block',marginBottom:12}}/>}<div style={{display:'flex',gap:18,marginBottom:22}}><button type="button" className="text-link" onClick={()=>inputs.current[index]?.click()}>{busy===index?'Preparing portrait…':profile.photo?'Change portrait':'Add portrait'}</button>{profile.photo&&<button type="button" className="text-link" onClick={()=>patch(index,{photo:''})}>Remove portrait</button>}</div><label className="field"><span>A little introduction <small>(optional)</small></span><textarea rows={3} value={profile.intro} maxLength={500} placeholder="A few words that sound like you." onChange={e=>patch(index,{intro:e.target.value})}/></label>{couple.showFamily&&<><label className="field"><span>Family name or heading <small>(optional)</small></span><input value={profile.familyName} maxLength={100} placeholder="e.g. The Kapoor family" onChange={e=>patch(index,{familyName:e.target.value})}/></label><label className="field"><span>Parents, guardians or loved ones <small>(optional)</small></span><textarea value={profile.guardians} rows={2} maxLength={200} placeholder="Write this in your own words." onChange={e=>patch(index,{guardians:e.target.value})}/></label></>}</fieldset>)}</>}</div>
}
