import {useState,type FormEvent} from 'react';
import {ArrowRight,EnvelopeSimple} from '@phosphor-icons/react';
import {api,ApiRequestError,setCsrf,type SessionUser} from './api';

export default function CustomerOtpAuth({onAuthenticated,compact=false}:{onAuthenticated:(user:SessionUser)=>void;compact?:boolean}){
 const [step,setStep]=useState<'email'|'code'|'name'>('email');const [email,setEmail]=useState('');const [name,setName]=useState('');const [code,setCode]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function request(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await api('/api/auth/otp/request',{method:'POST',body:JSON.stringify({email,purpose:'customer'})});setStep('code')}catch(reason){setError(reason instanceof Error?reason.message:'Could not email your code')}finally{setBusy(false)}}
 async function verify(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const result=await api<{user:SessionUser}>('/api/auth/otp/verify',{method:'POST',body:JSON.stringify({email,name,code,purpose:'customer'})});setCsrf(result.user.csrfToken);onAuthenticated(result.user)}catch(reason){if(reason instanceof ApiRequestError&&reason.code==='name_required'){setStep('name');setError('');return}setError(reason instanceof Error?reason.message:'Could not sign in')}finally{setBusy(false)}}
 const prompt=step==='email'?'Enter your email. We’ll send a private six-digit sign-in code.':step==='code'?'Enter the newest code from your email.':'This email is new to Vowvel. What should we call you?';
 return <form className={compact?'checkout-auth':'customer-otp-auth'} onSubmit={step==='email'?request:verify}>{!compact&&<EnvelopeSimple size={30}/>}<p>{prompt}</p>{step==='email'?<label>Email<input value={email} onChange={event=>setEmail(event.target.value)} type="email" required autoComplete="email" autoFocus/></label>:step==='code'?<label>Six-digit code<input value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,'').slice(0,6))} required inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} autoComplete="one-time-code" autoFocus/></label>:<label>Your name<input value={name} onChange={event=>setName(event.target.value)} required autoComplete="name" maxLength={100} autoFocus/></label>}{error&&<p className="notice checkout-error" role="alert">{error}</p>}<button className="button full" disabled={busy||(step==='code'&&code.length!==6)}>{busy?'Please wait':step==='email'?'Email me a code':step==='code'?'Verify code':'Create my account'} <ArrowRight/></button>{step!=='email'&&<button type="button" className="text-button full" onClick={()=>{setStep('email');setCode('');setName('');setError('')}}>Use a different email</button>}</form>;
}
