import {useCallback,useEffect,useState} from 'react';
import {ArrowClockwise,DownloadSimple,SignOut,UsersThree} from '@phosphor-icons/react';
import {Brand,navigate} from './App';
import {api,loadSession,setCsrf,type SessionUser} from './api';
import {normalizeDraft,saveDraft} from './storage';
import CustomerOtpAuth from './CustomerOtpAuth';
import './guest-replies.css';
import './guest-otp.css';

interface InvitationSummary{id:string;slug:string;state:string;response_count:number;attending_count:number;declined_count:number;created_at:string;updated_at:string}
interface ReplyEvent{id:string;name:string}
interface GuestReply{id:string;guest_name:string;email:string|null;attendance:'yes'|'no';party_size:number;guest_names:string;dietary_notes:string;message:string;created_at:string;updated_at:string;events:ReplyEvent[]}
const csv=(value:unknown)=>`"${String(value??'').replace(/"/g,'""').replace(/^([=+\-@])/,'\t$1')}"`;

export default function GuestReplies(){
  const [user,setUser]=useState<SessionUser|null>(null);const [checking,setChecking]=useState(true);const [invitations,setInvitations]=useState<InvitationSummary[]>([]);const [selectedId,setSelectedId]=useState('');const [replies,setReplies]=useState<GuestReply[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const loadInvitations=useCallback(async()=>{const result=await api<{invitations:InvitationSummary[]}>('/api/customer/invitations');setInvitations(result.invitations);setSelectedId(current=>result.invitations.some(item=>item.id===current)?current:result.invitations[0]?.id||'')},[]);
  useEffect(()=>{loadSession().then(session=>{if(session?.role==='customer')setUser(session)}).catch(()=>undefined).finally(()=>setChecking(false))},[]);
  useEffect(()=>{if(user)void loadInvitations().catch(reason=>setError(reason instanceof Error?reason.message:'Could not load your invitations'))},[user,loadInvitations]);
  const loadReplies=useCallback(async()=>{if(!selectedId){setReplies([]);return}setBusy(true);setError('');try{const result=await api<{rsvps:GuestReply[]}>(`/api/customer/invitations/${encodeURIComponent(selectedId)}/rsvps`);setReplies(result.rsvps)}catch(reason){setError(reason instanceof Error?reason.message:'Could not load guest replies')}finally{setBusy(false)}},[selectedId]);
  useEffect(()=>{if(user)void loadReplies()},[user,loadReplies]);
  async function logout(){await api('/api/auth/logout',{method:'POST'}).catch(()=>undefined);setCsrf('');setUser(null);setInvitations([]);setReplies([])}
  async function editInvitation(){if(!selectedId)return;setBusy(true);setError('');try{const result=await api<{payload:unknown;invitation:{editable:boolean;editableUntil:string|null}}> (`/api/customer/invitations/${encodeURIComponent(selectedId)}`);if(!result.invitation.editable)throw new Error('This celebration has passed, so the invitation is now read-only.');const draft=normalizeDraft(result.payload);if(!draft||!saveDraft(draft))throw new Error('The invitation could not be prepared for editing on this device.');navigate(`/create/${draft.theme}?update=${encodeURIComponent(selectedId)}`)}catch(reason){setError(reason instanceof Error?reason.message:'Could not open the invitation editor')}finally{setBusy(false)}}
  function exportCsv(){const rows=[['Guest','Email','Reply','Party size','Events','Additional guests','Dietary / accessibility','Note','Updated'],...replies.map(reply=>[reply.guest_name,reply.email||'',reply.attendance==='yes'?'Attending':'Declined',reply.party_size,reply.events.map(item=>item.name).join('; '),reply.guest_names,reply.dietary_notes,reply.message,reply.updated_at])];const blob=new Blob(['\ufeff'+rows.map(row=>row.map(csv).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`vowvel-guest-replies-${new Date().toISOString().slice(0,10)}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  if(checking)return <main className="replies-loading">Opening your guest list…</main>;
  if(!user)return <main className="replies-auth"><header><Brand/><button onClick={()=>navigate('/')}>Back to Vowvel</button></header><section className="replies-login"><span className="replies-kicker">YOUR INVITATION</span><h1>Guest replies,<br/><em>all together.</em></h1><p>Use the email address connected to your invitation.</p><CustomerOtpAuth onAuthenticated={setUser}/></section></main>;
  const selected=invitations.find(item=>item.id===selectedId);const attending=replies.filter(item=>item.attendance==='yes').reduce((sum,item)=>sum+item.party_size,0);const declined=replies.filter(item=>item.attendance==='no').length;
  return <main className="replies-page"><header><Brand/><div><span>{user.name}</span><button onClick={()=>void logout()}><SignOut/> Sign out</button></div></header><section className="replies-hero"><div><span className="replies-kicker"><UsersThree/> GUEST REPLIES</span><h1>Your celebration,<br/><em>coming together.</em></h1><p>Every reply is saved here. Guests can update their own response from the same device.</p></div>{invitations.length>0&&<label>Invitation<select value={selectedId} onChange={event=>setSelectedId(event.target.value)}>{invitations.map(item=><option value={item.id} key={item.id}>{item.slug} · {item.state}</option>)}</select></label>}</section>{error&&<p className="replies-error" role="alert">{error}</p>}{!selected?<section className="replies-empty"><h2>No published invitation yet.</h2><p>Your guest list appears here after an invitation is published.</p><button className="replies-primary" onClick={()=>navigate('/')}>Choose a design</button></section>:<><section className="replies-metrics"><article><span>Replies</span><strong>{replies.length}</strong><small>households</small></article><article><span>Attending</span><strong>{attending}</strong><small>guests</small></article><article><span>Declined</span><strong>{declined}</strong><small>households</small></article></section><section className="replies-list"><div className="replies-list-head"><div><h2>The guest list</h2><p>For <a href={`/invitation/${selected.slug}`} target="_blank" rel="noreferrer">{selected.slug} ↗</a></p></div><div><button onClick={()=>void editInvitation()} disabled={busy}>Edit invitation</button><button onClick={()=>void loadReplies()} disabled={busy}><ArrowClockwise/> Refresh</button><button onClick={exportCsv} disabled={!replies.length}><DownloadSimple/> Export CSV</button></div></div>{busy?<p className="replies-status">Refreshing replies…</p>:replies.length===0?<div className="replies-empty compact"><h3>No replies just yet.</h3><p>Share your invitation link; new responses will appear here.</p></div>:<div className="replies-grid">{replies.map(reply=><article key={reply.id}><div className="reply-title"><div><h3>{reply.guest_name}</h3><a href={reply.email?`mailto:${reply.email}`:undefined}>{reply.email||'No email supplied'}</a></div><span className={reply.attendance}>{reply.attendance==='yes'?`${reply.party_size} attending`:'Declined'}</span></div>{reply.events.length>0&&<dl><dt>Events</dt><dd>{reply.events.map(item=>item.name).join(' · ')}</dd></dl>}{reply.guest_names&&<dl><dt>Guests</dt><dd>{reply.guest_names}</dd></dl>}{reply.dietary_notes&&<dl><dt>Dietary / accessibility</dt><dd>{reply.dietary_notes}</dd></dl>}{reply.message&&<blockquote>“{reply.message}”</blockquote>}<time dateTime={reply.updated_at}>Updated {new Date(reply.updated_at+'Z').toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</time></article>)}</div>}</section></>}</main>;
}
