import {useEffect,useState} from 'react';
import {type InvitationData,themeById} from './data';
import {sharingDetails,sharingSvg} from './sharing';
import './sharing-preview.css';
export default function SharingPreview({data}:{data:InvitationData}){
 const [art,setArt]=useState('');const [error,setError]=useState('');const theme=themeById(data.theme);const meta=sharingDetails(data);
 useEffect(()=>{const abort=new AbortController();setArt('');setError('');fetch(`/films/${data.theme}-poster.webp`,{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error();return r.blob()}).then(blob=>{const reader=new FileReader();reader.onload=()=>{if(!abort.signal.aborted)setArt(String(reader.result))};reader.readAsDataURL(blob)}).catch(()=>{if(!abort.signal.aborted)setError('The sharing image could not load. Try changing the design.')});return()=>abort.abort()},[data.theme]);
 const svg=art?sharingSvg(data,theme,art):'';const src=svg?'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg):'';
 async function download(){try{await document.fonts.ready;const image=new Image();image.src=src;await image.decode();const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=630;canvas.getContext('2d')!.drawImage(image,0,0);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='vowvel-sharing-image.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setError('Could not export the image. Please try again.')}}
 return <details className="sharing-preview"><summary>Your link’s first impression</summary><p>Created automatically from your names, date and design.</p><div className="sharing-card">{src&&<img src={src} width="1200" height="630" alt={meta.imageAlt}/>}<div><small>VOWVEL · INVITATION</small><h3>{meta.title}</h3><p>{meta.description}</p></div></div><button type="button" className="text-link" disabled={!art} onClick={download}>Download sharing image ↗</button>{error&&<p role="alert">{error}</p>}<p className="sharing-note">Preview of the image guests see when you share your live link after you publish.</p></details>
}
